version: 2.1 
orbs:
    node: circleci/node@4.1.0
    aws-cli: circleci/aws-cli@1.3.1
    eb: circleci/aws-elastic-beanstalk@2.0.1
jobs:
    build: 
        docker:
            - image: "cimg/base:stable"  
        steps:
            - node/install
            - checkout
            - run: node --version
            - run:
                name: Get and install node version manager.
                command: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
            - run:
                name: Install Node version 14 using NVM
                command: nvm install 14 
            - run:
                name: Use Node version 14 
                command: nvm use 14  
            - run:
                name: Swap node versions
                command: |
                    set +e
                    wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.1/install.sh | bash
                    export NVM_DIR="$HOME/.nvm"
                    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
                    [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
                    nvm install v14
                    nvm alias default 14.19.1

                    echo 'export NVM_DIR="$HOME/.nvm"' >> $BASH_ENV
                    echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> $BASH_ENV
            - run:
                  name: Front-End Install
                  command: |
                    npm run frontend:install
            - run:
                  name: Back-End Install
                  command: |
                    npm run backend:install
            - run:
                  name: Front-End Build
                  command: |
                    npm run frontend:build
            - run:
                  name: Back-End Build
                  command: |
                    npm run backend:build                

            - node/install
            - checkout
            - aws-cli/setup
            - run:
                name: front-End deploy
                command: |
                        npm run frontend:deploy
            - node/install
            - checkout
            - eb/setup
            - run: sudo apt-get -y -qq update --assume-yes
            - run: sudo apt-get install python3-pip python-dev build-essential --assume-yes
            - run: sudo pip install awsebcli --upgrade
            - run: eb init udagram-ebservice --platform Node.js --region 'us-east-1' -yes
            - run:
                name: Back-End deploy
                command: |
                        npm run backend:deploy                
workflows:
   version: 2
   build and deploy:
       jobs:
           - build:   
                filters:
                      branches: 
                          only: main 
           
               
                       
                    
                 
             
                 