version: 2.1 
orbs:
    node: circleci/node@4.1.0
    aws-cli: circleci/aws-cli@1.3.1
jobs:
    build: 
        docker:
            - image: "cimg/base:stable"
            
        steps:
            - checkout
            - run:
                name: install-node
                command: sudo npm install -g node@16.13.2
            - run: node --version
            - run:
                  name: Front-End Install
                  command: |
                    npm run frontend:install
            - run:
                  name: Back-End Install
                  command: |
                    npm run backend:install
            - run:
                  name: Front-End Build
                  command: |
                    npm run frontend:build
            - run:
                  name: Back-End Build
                  command: |
                    npm run backend:build
    deploy:
        docker:
            - image: "cimg/base:stable"

        steps:
            - node/install
            - checkout
            - aws-cli/setup
            - run:
                  name: front-End deploy
                  command: |
                    npm run frontend:deploy
    deploy-backend:
        docker:
            - image: "cimg/base:stable"

        steps:
            - node/install
            - checkout
            - aws-cli/setupb
            - node/with-cache:

                  steps:
                       - run:
                            name: Installing deployment dependencies
                            command: |
                                sudo apt-get -y -qq update
                                sudo apt install python-pip python-dev build essential
                                sudo pip install --upgrade setuptools
                                sudo pip install awsebcli --upgrade
                       - run:
                            name: Back-End deploy
                            command: |
                               npm run backend:deploy                
workflows:
   version: 2
   build and deploy:
       jobs:
           - build:   
                filters:
                      branches: 
                          only: main 
           - deploy:
                    requires:
                         - build
               
                       
                    
                 
             
                 